nav:
  home: /
  about: /2021/05/Gh20210550500ba30d6226d6522402fba2d67799/
  articles: /archives/
  
social_links:
  github: http://github.com/whyouare111
  mail: mailto:whyouare556@protonmail.com

colorscheme: "dark"
